version: '3'

services:
  web:
    build: .
    container_name: qr_code_generator
    ports:
      - "5001:5000"
    volumes:
      - ./qrcodes:/app/qrcodes
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

