apiVersion: v1
kind: Service
metadata:
  name: qr-code-service
spec:
  type: NodePort
  selector:
    app: qr-code-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080 

